name: Deploy GitHub Pages
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build Flutter Web
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'dev'
      - run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: master
          publish_dir: ./public